bump_version: null
lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - conf/igenomes.config
  - conf/igenomes_ignored.config
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Ziad Al-Bkhetan and Thomas Liftin
  description: Workflow for Interaction Screening by predicting Structure
  force: true
  is_nfcore: true
  name: wisps
  org: nf-core
  outdir: .
  skip_features:
  - igenomes
  - fastqc
  version: 1.0.0dev
update: null
